### ISSUE TITLE
Error with emg_filter.py: Hard coded file path?

### ISSUE THREAD

**Issue by natashakbt** [abuzarmahmood/blech_clust#160]
Hello! Ran into an error with `emg_filter.py`. Looks like the code might be looking for a hard coded file path? Message below:
```
Traceback (most recent call last):
  File "emg_filter.py", line 20, in <module>
    metadata_handler = imp_metadata([[],dir_name])
  File "/home/natasha/Desktop/blech_clust/emg/../utils/blech_utils.py", line 28, in __init__
    self.get_file_list()
  File "/home/natasha/Desktop/blech_clust/emg/../utils/blech_utils.py", line 44, in get_file_list
    self.file_list = os.listdir(self.dir_name)
FileNotFoundError: [Errno 2] No such file or directory: '/media/bigdata/NM43_2500ms_160515_104159_copy/'
```

**Comment by abuzarmahmood** [comment]
For reference, this issue was related to commit e9a5857
