### ISSUE TITLE
ReadMe should have script usage instructions

### ISSUE THREAD

**Issue by emmalala123** [abuzarmahmood/blech_clust#170]
Just need the $DIR description --- when to use it when running certain functions. Thanks!

**Comment by abuzarmahmood** [comment]
The issue at hand involves updating the README file of the `blech_clust` repository to include detailed instructions on the usage of the `$DIR` variable. This variable is crucial for setting the path to raw data files needed for processing by the scripts in the repository.

### Suggestions and Changes Made:

1. **File to Modify**:
   - **File**: `/home/exouser/Desktop/blech_github_bot/src/repos/katzlabbrandeis/blech_clust/README.md`
   - **Description**: This file serves as the main documentation for the `blech_clust` repository, detailing the order of operations, setup instructions, and workflow walkthroughs. The `$DIR` variable is mentioned in the context of setting the path to raw data files for processing.

2. **Plan to Address the Issue**:
   - Enhance the README file by adding a detailed explanation of the `$DIR` variable, including when and how it should be used in the context of running scripts within the repository.

3. **Specific Changes**:
   - **Add Explanation for `$DIR` Usage**:
     - **Line**: 128-130
     - **Description of Change**: Add a detailed explanation of the `$DIR` variable, including its purpose and how it should be set before running scripts. This will help users understand the importance of `$DIR` in the workflow and ensure they set it correctly.
     - **Code Snippet of Edits**:
       ```markdown
       ### Setting the `$DIR` Variable

       Before running any scripts, you need to set the `$DIR` variable to the path where your raw data files are located. This variable is crucial as it tells the scripts where to find the data they need to process. You can set it using the following command:

       ```bash
       DIR=/path/to/raw/data/files
       ```

       Make sure to replace `/path/to/raw/data/files` with the actual path to your data files. This step is necessary before running scripts like `blech_exp_info.py`, which require access to the raw data for processing.
       ```

By implementing these changes, the README will provide clearer guidance on using the `$DIR` variable, aiding users in correctly setting up and running the scripts in the `blech_clust` repository.

---
*This response was automatically generated by blech_bot*

**Comment by abuzarmahmood** [comment]
To address the user's feedback about including information on all scripts that require the path to the data directory as input, we can enhance the README file with additional details. Here's an updated response incorporating the feedback:

### Updated Suggestions and Changes:

1. **File to Modify**:
   - **File**: `/home/exouser/Desktop/blech_github_bot/src/repos/katzlabbrandeis/blech_clust/README.md`
   - **Description**: This file serves as the main documentation for the `blech_clust` repository, detailing the order of operations, setup instructions, and workflow walkthroughs. The `$DIR` variable is mentioned in the context of setting the path to raw data files for processing.

2. **Plan to Address the Issue**:
   - Enhance the README file by adding a detailed explanation of the `$DIR` variable, including when and how it should be used in the context of running scripts within the repository.
   - Include a list of scripts that require the path to the data directory as input, along with a brief description of their purpose.

3. **Specific Changes**:
   - **Add Explanation for `$DIR` Usage**:
     - **Line**: 128-130
     - **Description of Change**: Add a detailed explanation of the `$DIR` variable, including its purpose and how it should be set before running scripts. This will help users understand the importance of `$DIR` in the workflow and ensure they set it correctly.
     - **Code Snippet of Edits**:
       ```markdown
       ### Setting the `$DIR` Variable

       Before running any scripts, you need to set the `$DIR` variable to the path where your raw data files are located. This variable is crucial as it tells the scripts where to find the data they need to process. You can set it using the following command:

       ```bash
       DIR=/path/to/raw/data/files
       ```

       Make sure to replace `/path/to/raw/data/files` with the actual path to your data files. This step is necessary before running scripts like `blech_exp_info.py`, which require access to the raw data for processing.
       ```

   - **Add List of Scripts Requiring Data Directory Path**:
     - **Line**: 132-140 (after the `$DIR` explanation)
     - **Description of Change**: Add a list of scripts that require the data directory path as input, along with a brief description of each script's purpose.
     - **Code Snippet of Edits**:
       ```markdown
       ### Scripts Requiring the Data Directory Path

       The following scripts require the `$DIR` variable to be set to the path of your data directory:

       - `blech_exp_info.py`: Generates a file containing relevant experimental information for a given dataset.
       - `blech_process.py`: Processes single electrode waveforms for spike detection and clustering.
       - `blech_make_arrays.py`: Processes neural and EMG data from an HDF5 file, extracting and organizing spike trains and EMG trials.
       - `blech_post_process.py`: Handles the final stage of spike sorting, allowing both manual and automatic processing of clustered neural data.
       - `blech_clust.py`: Main script for processing and clustering neural recording data, creating an HDF5 file structure to store the processed data.

       Ensure that the `$DIR` variable is correctly set before executing these scripts to avoid any errors during processing.
       ```

By implementing these changes, the README will provide clearer guidance on using the `$DIR` variable and inform users about the scripts that require the data directory path, aiding them in correctly setting up and running the scripts in the `blech_clust` repository.

---
*This response was automatically generated by blech_bot using model gpt-4o*

**Comment by abuzarmahmood** [comment]
[ develop_issue ]

**Comment by abuzarmahmood** [comment]
Error processing issue #170: ERROR: Failed to process develop issue: Unexpected error running aider: No changes made by Aider

```
Traceback (most recent call last):
  File "/home/exouser/Desktop/blech_github_bot/src/response_agent.py", line 1127, in run_aider
    raise RuntimeError("No changes made by Aider")
RuntimeError: No changes made by Aider

```

```
Traceback (most recent call last):
  File "/home/exouser/Desktop/blech_github_bot/src/response_agent.py", line 1127, in run_aider
    raise RuntimeError("No changes made by Aider")
RuntimeError: No changes made by Aider

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/exouser/Desktop/blech_github_bot/src/response_agent.py", line 721, in develop_issue_flow
    aider_output = run_aider(response, repo_path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/exouser/Desktop/blech_github_bot/src/response_agent.py", line 1145, in run_aider
    raise RuntimeError(error_msg)
RuntimeError: Unexpected error running aider: No changes made by Aider

```
Traceback (most recent call last):
  File "/home/exouser/Desktop/blech_github_bot/src/response_agent.py", line 1127, in run_aider
    raise RuntimeError("No changes made by Aider")
RuntimeError: No changes made by Aider

```

```

```
Traceback (most recent call last):
  File "/home/exouser/Desktop/blech_github_bot/src/response_agent.py", line 1127, in run_aider
    raise RuntimeError("No changes made by Aider")
RuntimeError: No changes made by Aider

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/exouser/Desktop/blech_github_bot/src/response_agent.py", line 721, in develop_issue_flow
    aider_output = run_aider(response, repo_path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/exouser/Desktop/blech_github_bot/src/response_agent.py", line 1145, in run_aider
    raise RuntimeError(error_msg)
RuntimeError: Unexpected error running aider: No changes made by Aider

```
Traceback (most recent call last):
  File "/home/exouser/Desktop/blech_github_bot/src/response_agent.py", line 1127, in run_aider
    raise RuntimeError("No changes made by Aider")
RuntimeError: No changes made by Aider

```

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/exouser/Desktop/blech_github_bot/src/response_agent.py", line 1054, in process_issue
    result, err_msg = develop_issue_flow(
                      ^^^^^^^^^^^^^^^^^^^
  File "/home/exouser/Desktop/blech_github_bot/src/response_agent.py", line 781, in develop_issue_flow
    raise Exception(error_msg)
Exception: ERROR: Failed to process develop issue: Unexpected error running aider: No changes made by Aider

```
Traceback (most recent call last):
  File "/home/exouser/Desktop/blech_github_bot/src/response_agent.py", line 1127, in run_aider
    raise RuntimeError("No changes made by Aider")
RuntimeError: No changes made by Aider

```

```
Traceback (most recent call last):
  File "/home/exouser/Desktop/blech_github_bot/src/response_agent.py", line 1127, in run_aider
    raise RuntimeError("No changes made by Aider")
RuntimeError: No changes made by Aider

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/exouser/Desktop/blech_github_bot/src/response_agent.py", line 721, in develop_issue_flow
    aider_output = run_aider(response, repo_path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/exouser/Desktop/blech_github_bot/src/response_agent.py", line 1145, in run_aider
    raise RuntimeError(error_msg)
RuntimeError: Unexpected error running aider: No changes made by Aider

```
Traceback (most recent call last):
  File "/home/exouser/Desktop/blech_github_bot/src/response_agent.py", line 1127, in run_aider
    raise RuntimeError("No changes made by Aider")
RuntimeError: No changes made by Aider

```

```

```

---
*This response was automatically generated by blech_bot using model gpt-4o*

**Comment by abuzarmahmood** [comment]
Error processing issue #170: ERROR: Failed to process develop issue: Unexpected error running aider: No changes made by Aider

```
Traceback (most recent call last):
  File "/home/exouser/Desktop/blech_github_bot/src/response_agent.py", line 1127, in run_aider
    raise RuntimeError("No changes made by Aider")
RuntimeError: No changes made by Aider

```

```
Traceback (most recent call last):
  File "/home/exouser/Desktop/blech_github_bot/src/response_agent.py", line 1127, in run_aider
    raise RuntimeError("No changes made by Aider")
RuntimeError: No changes made by Aider

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/exouser/Desktop/blech_github_bot/src/response_agent.py", line 721, in develop_issue_flow
    aider_output = run_aider(response, repo_path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/exouser/Desktop/blech_github_bot/src/response_agent.py", line 1145, in run_aider
    raise RuntimeError(error_msg)
RuntimeError: Unexpected error running aider: No changes made by Aider

```
Traceback (most recent call last):
  File "/home/exouser/Desktop/blech_github_bot/src/response_agent.py", line 1127, in run_aider
    raise RuntimeError("No changes made by Aider")
RuntimeError: No changes made by Aider

```

```

```
Traceback (most recent call last):
  File "/home/exouser/Desktop/blech_github_bot/src/response_agent.py", line 1127, in run_aider
    raise RuntimeError("No changes made by Aider")
RuntimeError: No changes made by Aider

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/exouser/Desktop/blech_github_bot/src/response_agent.py", line 721, in develop_issue_flow
    aider_output = run_aider(response, repo_path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/exouser/Desktop/blech_github_bot/src/response_agent.py", line 1145, in run_aider
    raise RuntimeError(error_msg)
RuntimeError: Unexpected error running aider: No changes made by Aider

```
Traceback (most recent call last):
  File "/home/exouser/Desktop/blech_github_bot/src/response_agent.py", line 1127, in run_aider
    raise RuntimeError("No changes made by Aider")
RuntimeError: No changes made by Aider

```

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/exouser/Desktop/blech_github_bot/src/response_agent.py", line 1054, in process_issue
    result, err_msg = develop_issue_flow(
                      ^^^^^^^^^^^^^^^^^^^
  File "/home/exouser/Desktop/blech_github_bot/src/response_agent.py", line 781, in develop_issue_flow
    raise Exception(error_msg)
Exception: ERROR: Failed to process develop issue: Unexpected error running aider: No changes made by Aider

```
Traceback (most recent call last):
  File "/home/exouser/Desktop/blech_github_bot/src/response_agent.py", line 1127, in run_aider
    raise RuntimeError("No changes made by Aider")
RuntimeError: No changes made by Aider

```

```
Traceback (most recent call last):
  File "/home/exouser/Desktop/blech_github_bot/src/response_agent.py", line 1127, in run_aider
    raise RuntimeError("No changes made by Aider")
RuntimeError: No changes made by Aider

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/exouser/Desktop/blech_github_bot/src/response_agent.py", line 721, in develop_issue_flow
    aider_output = run_aider(response, repo_path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/exouser/Desktop/blech_github_bot/src/response_agent.py", line 1145, in run_aider
    raise RuntimeError(error_msg)
RuntimeError: Unexpected error running aider: No changes made by Aider

```
Traceback (most recent call last):
  File "/home/exouser/Desktop/blech_github_bot/src/response_agent.py", line 1127, in run_aider
    raise RuntimeError("No changes made by Aider")
RuntimeError: No changes made by Aider

```

```

```

---
*This response was automatically generated by blech_bot using model gpt-4o*
