### ISSUE TITLE
Issues with xgboost

### ISSUE THREAD

**Issue by Mraymon5** [abuzarmahmood/blech_clust#179]
Having trouble running
bash blech_run_process.sh

Trying to take it in steps, and running into an issue with blech_process.py:

Traceback (most recent call last):
  File "blech_process.py", line 152, in <module>
    classifier_handler.load_pipelines()
  File "/home/ramartin/blech_clust/utils/blech_process_utils.py", line 588, in load_pipelines
    self.pred_pipeline = load(self.pred_pipeline_path)
  File "/home/ramartin/anaconda3/envs/blech_clust/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 587, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/home/ramartin/anaconda3/envs/blech_clust/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 506, in _unpickle
    obj = unpickler.load()
  File "/home/ramartin/anaconda3/envs/blech_clust/lib/python3.8/pickle.py", line 1212, in load
    dispatch[key[0]](self)
  File "/home/ramartin/anaconda3/envs/blech_clust/lib/python3.8/pickle.py", line 1528, in load_global
    klass = self.find_class(module, name)
  File "/home/ramartin/anaconda3/envs/blech_clust/lib/python3.8/pickle.py", line 1583, in find_class
    return getattr(sys.modules[module], name)
AttributeError: module 'xgboost.compat' has no attribute 'XGBoostLabelEncoder'

It looks like maybe the people running XGBoost just totally nixed that whole function:
https://github.com/dmlc/xgboost/issues/6209

I'll try to work through the problem and see if I can figure it out, but yeah, I think there's a compatibility issue with the newest version of xgboost.

**Comment by abuzarmahmood** [comment]
That's weird because we use a specific version of xgboost. Could you check that the version you have in your environment is the same version specificied in the requirements (`1.5.0`)?

**Comment by Mraymon5** [comment]
It is definitely not! Oops. I uninstalled and reinstalled it at some point to try and do... something (don't remember), so that's the issue. I'll re-run the compatibility stuff.

**Comment by Mraymon5** [comment]
Yeah, reran the requirements downloads, and that fixed the xgboost issue.

**Comment by abuzarmahmood** [comment]
Glad to hear it :)
