### ISSUE TITLE
Error saving clustermap.png during cluster_stability.py

### ISSUE THREAD

**Issue by Mraymon5** [abuzarmahmood/blech_clust#188]
When running clusterstability.py, or any of the .sh programs that include it, I'm getting this error:
```
Traceback (most recent call last):
  File "./utils/cluster_stability.py", line 135, in <module>
    fig.savefig(f'./Plots/{electrode_num:02}/clusters{clust_num:02}/' +\
  File "/home/ramartin/anaconda3/envs/blech_test/lib/python3.8/site-packages/matplotlib/figure.py", line 2311, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/ramartin/anaconda3/envs/blech_test/lib/python3.8/site-packages/matplotlib/backends/backend_qt5agg.py", line 81, in print_figure
    super().print_figure(*args, **kwargs)
  File "/home/ramartin/anaconda3/envs/blech_test/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2210, in print_figure
    result = print_method(
  File "/home/ramartin/anaconda3/envs/blech_test/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 1639, in wrapper
    return func(*args, **kwargs)
  File "/home/ramartin/anaconda3/envs/blech_test/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 510, in print_png
    mpl.image.imsave(
  File "/home/ramartin/anaconda3/envs/blech_test/lib/python3.8/site-packages/matplotlib/image.py", line 1611, in imsave
    image.save(fname, **pil_kwargs)
  File "/home/ramartin/anaconda3/envs/blech_test/lib/python3.8/site-packages/PIL/Image.py", line 2563, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/home/ramartin/Documents/MAR_Data/MR03/MR03_BAT-Tastes-Day7_TEST_240527_132310/Plots/00/clusters02/clustermap.png'
```

I think I've figured that out:
In `cluster_stability.py` line 135:
```
fig.savefig(f'./Plots/{electrode_num:02}/clusters{clust_num:02}/' +\
		f'clustermap.png', dpi=300,
		bbox_inches='tight')
```
Having `clusters{clust_num:02} ` sets the file naming convention to cluster0X with a leading 0 for single digits, rather than clusterX.
The folders are originally named in `blech_process_utils.py`  line 237, and there the code is
` f'clusters{self.cluster_num}'`, without the leading 0.

I kind of like the leading 0, but I think changing the folder naming in `blech_process_utils.py` is very likely to create downstream issues, so the simplest solution is to change line 135 in `cluster_stability.py` to
```
	fig.savefig(f'./Plots/{electrode_num:02}/clusters{clust_num}/' +\
```

**Comment by Mraymon5** [comment]
Oops forgot this was already addressed in issue 186! Sorry!
