### ISSUE TITLE
blech_run_QA lacks pingouin 

### ISSUE THREAD

**Issue by Mraymon5** [abuzarmahmood/blech_clust#197]
Running blech_run_QA.sh produces this issue:

```
Running Drift test
Traceback (most recent call last):
  File "/home/ramartin/blech_clust-180-issues-with-blech_processpy/utils/qa_utils/drift_check.py", line 21, in <module>
    import pingouin as pg
ModuleNotFoundError: No module named 'pingouin'
```

Installed pingouin, re-ran, and produced a new error:
```
Running Drift test
Processing : /home/ramartin/Documents/MAR_Data/MR03/MR03_BAT-Tastes-Day7_240527_132310/
Traceback (most recent call last):
  File "/home/ramartin/blech_clust-180-issues-with-blech_processpy/utils/qa_utils/drift_check.py", line 92, in <module>
    spike_trains = get_spike_trains(metadata_handler.hdf5_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ramartin/blech_clust-180-issues-with-blech_processpy/utils/qa_utils/drift_check.py", line 42, in get_spike_trains
    dig_ins = hf5.list_nodes('/spike_trains') 
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ramartin/anaconda3/lib/python3.11/site-packages/tables/file.py", line 1958, in list_nodes
    group = self.get_node(where)  # Does the parent exist?
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/ramartin/anaconda3/lib/python3.11/site-packages/tables/file.py", line 1603, in get_node
    node = self._get_node(nodepath)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ramartin/anaconda3/lib/python3.11/site-packages/tables/file.py", line 1550, in _get_node
    node = self._node_manager.get_node(nodepath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ramartin/anaconda3/lib/python3.11/site-packages/tables/file.py", line 411, in get_node
    node = self.node_factory(key)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ramartin/anaconda3/lib/python3.11/site-packages/tables/group.py", line 1137, in _g_load_child
    node_type = self._g_check_has_child(childname)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ramartin/anaconda3/lib/python3.11/site-packages/tables/group.py", line 375, in _g_check_has_child
    raise NoSuchNodeError(
tables.exceptions.NoSuchNodeError: group ``/`` does not have a child named ``/spike_trains``
```

**Comment by Mraymon5** [comment]
Seems like the pingouin issue could be resolved with another edit to "conda_requirements_base.sh"

Going to try to look into the `/spike_trains` thing

**Comment by abuzarmahmood** [comment]
the spike trains get generated in blech_make_arrays...if your conda environment wasn't activated, my guess is that blech_make_arrays didn't succeed. I would restart the pipeline from there with the right environment.

I've been wanting a way to have subsequent steps only run if previous steps run successfully (#45 and #113)...that would actually catch a bunch of these kinds of issues. I might try to work on that given the preponderance scenarios where upstream errors are missed

**Comment by Mraymon5** [comment]
Okay, well first off, activating the environment immediately solved the pingouin issue, so that was a user error problem.

With respect to the missing spike_trains, I haven't actually run `blech_make_arrays`; it appears in the workflow flow chart after `blech_run_QA`. Am I just taking things in the wrong order?

**Comment by abuzarmahmood** [comment]
Ah lol...I thought I'd heard before  what you just said...this is a known bug in the flowchart ::: #176.
I'd appreciate if you have time to take a whack at fixing the flow-chart (the instructions are in the Readme)...otherwise I should be able to get to it soon
